TRUNCATE articles RESTART IDENTITY;

TRUNCATE myths RESTART IDENTITY;

TRUNCATE facts RESTART IDENTITY CASCADE ;

TRUNCATE funds RESTART IDENTITY CASCADE ;

TRUNCATE medias RESTART IDENTITY CASCADE ;
